[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[env]
ASSETS_SERVER_ASSETS_DIR = { value = "./assets", relative = true }
ASSETS_SERVER_MAPPING_FILE = { value = "./assets/game_assets_mapping.json", relative = true }

GAME_HOST_SERVER_PROGRAMS_DIR = { value = "./assets", relative = false }
GAME_HOST_SERVER_MAPPING_FILE = { value = "./assets/game_dir_mapping.json", relatuve = false }

# This is for test exe of game_host_server
DEBUG_ECHO_PROGRAM_FILE = { value = "./target/debug/echo", relative = true}

# This is for building protobuf types.
PROTO_HOST_MANAGEMENT_INTERFACE_DIR = { value = "../savage_playground_communication/host_management_interface/proto", relative = true }
SCHEMA_HOST_MANAGEMENT_INTERFACE_DIR = { value = "../savage_playground_communication/host_management_interface/schema", relative = true }

PROTO_HOST_RUNTIME_INTERFACE_DIR = { value = "../savage_playground_communication/host_runtime_interface/proto", relative = true }
PROTO_GAME_INTERFACE_DIR = { value = "../savage_playground_communication/game_interface/proto", relative = true }
