[package]
name = "game_interface"
description = "Defines types used to communicate with the game."
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "*"
prost-types = "*"

[build-dependencies]
proto_gen = { path = "../../utils/proto_gen" }